# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
   pod 'image_picker_ios', :path =>'/Users/jigar/Documents/Jigar/Projects/DULTRA/datacare_ultra/ios/.symlinks/plugins/image_picker_ios/ios'
   pod 'path_provider_foundation', :path =>'/Users/jigar/Documents/Jigar/Projects/DULTRA/datacare_ultra/ios/.symlinks/plugins/path_provider_foundation/darwin'
   pod 'share_plus', :path =>'/Users/jigar/Documents/Jigar/Projects/DULTRA/datacare_ultra/ios/.symlinks/plugins/share_plus/ios'
   pod 'shared_preferences_foundation', :path =>'/Users/jigar/Documents/Jigar/Projects/DULTRA/datacare_ultra/ios/.symlinks/plugins/shared_preferences_foundation/darwin'
   pod 'sqflite_darwin', :path =>'/Users/jigar/Documents/Jigar/Projects/DULTRA/datacare_ultra/ios/.symlinks/plugins/sqflite_darwin/darwin'
   pod 'url_launcher_ios', :path =>'/Users/jigar/Documents/Jigar/Projects/DULTRA/datacare_ultra/ios/.symlinks/plugins/url_launcher_ios/ios'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
